### ISSUE TITLE
Please specify the version of libuv that we need to checkout

### ISSUE THREAD

**Issue by nuclear-waste-storage** [wehu/mo#1]
I've got 'Segmentation fault' after successful build on v0.6

Thanks.

**Comment by nuclear-waste-storage** [comment]
I'm not familiar enough with C, I will appreciate any help

More information:
(gdb) backtrace
#0  0x00007fe98869acf1 in ?? () from /usr/lib/x86_64-linux-gnu/libguile-2.0.so.22
#1  0x00007fe9886babf1 in ?? () from /usr/lib/x86_64-linux-gnu/libguile-2.0.so.22
#2  0x00007fe9885eab87 in scm_call_1 () from /usr/lib/x86_64-linux-gnu/libguile-2.0.so.22
#3  0x00007fe98868808a in scm_call_with_input_string () from /usr/lib/x86_64-linux-gnu/libguile-2.0.so.22
#4  0x00007fe98869aa14 in ?? () from /usr/lib/x86_64-linux-gnu/libguile-2.0.so.22
#5  0x00007fe9886babf1 in ?? () from /usr/lib/x86_64-linux-gnu/libguile-2.0.so.22
#6  0x00007fe9885eac4b in scm_call_3 () from /usr/lib/x86_64-linux-gnu/libguile-2.0.so.22
#7  0x00007fe98868834b in scm_eval_string_in_module () from /usr/lib/x86_64-linux-gnu/libguile-2.0.so.22
#8  0x00007fe98868836f in scm_eval_string () from /usr/lib/x86_64-linux-gnu/libguile-2.0.so.22
#9  0x00007fe988688227 in scm_c_eval_string () from /usr/lib/x86_64-linux-gnu/libguile-2.0.so.22
#10 0x0000559f0a07692c in Mo::Logger::RegisterSCMFunctions () at src/mo_logger.cpp:88
#11 0x0000559f0a0737e2 in Mo::Main::RegisterSCMFunctions () at src/mo.cpp:46
#12 0x0000559f0a071e10 in inner_main (data=<optimized out>, argc=2, argv=0x7fff043ea9b8) at src/main.cpp:26
#13 0x00007fe988614412 in ?? () from /usr/lib/x86_64-linux-gnu/libguile-2.0.so.22
#14 0x00007fe9885e0209 in ?? () from /usr/lib/x86_64-linux-gnu/libguile-2.0.so.22
#15 0x00007fe988690458 in ?? () from /usr/lib/x86_64-linux-gnu/libguile-2.0.so.22
#16 0x00007fe988662353 in ?? () from /usr/lib/x86_64-linux-gnu/libguile-2.0.so.22
#17 0x00007fe98869aa14 in ?? () from /usr/lib/x86_64-linux-gnu/libguile-2.0.so.22
#18 0x00007fe9886babf1 in ?? () from /usr/lib/x86_64-linux-gnu/libguile-2.0.so.22
#19 0x00007fe9885eacc9 in scm_call_4 () from /usr/lib/x86_64-linux-gnu/libguile-2.0.so.22
#20 0x00007fe9886902ae in scm_catch_with_pre_unwind_handler () from /usr/lib/x86_64-linux-gnu/libguile-2.0.so.22
#21 0x00007fe988690530 in scm_c_catch () from /usr/lib/x86_64-linux-gnu/libguile-2.0.so.22
#22 0x00007fe9885e0058 in ?? () from /usr/lib/x86_64-linux-gnu/libguile-2.0.so.22
#23 0x00007fe9885e0321 in scm_c_with_continuation_barrier () from /usr/lib/x86_64-linux-gnu/libguile-2.0.so.22
#24 0x00007fe98868d224 in ?? () from /usr/lib/x86_64-linux-gnu/libguile-2.0.so.22
#25 0x00007fe9871c4c42 in GC_call_with_stack_base () from /usr/lib/x86_64-linux-gnu/libgc.so.1
#26 0x00007fe98868d30d in ?? () from /usr/lib/x86_64-linux-gnu/libguile-2.0.so.22
#27 0x00007fe98868d34d in scm_with_guile () from /usr/lib/x86_64-linux-gnu/libguile-2.0.so.22
#28 0x00007fe9886143a3 in scm_boot_guile () from /usr/lib/x86_64-linux-gnu/libguile-2.0.so.22
#29 0x0000559f0a071802 in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:47
